// Code generated by gocli

package eb_system_config_model

import (
	"crmeb_go/internal/model"
	"gorm.io/gorm"
	"time"
)

// EbSystemConfigModel 配置表 模型
type EbSystemConfigModel struct {
	model.DBModel
	ID         uint64    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:配置id" json:"id"`            // 配置id
	Name       string    `gorm:"column:name;type:varchar(255);not null;comment:字段名称" json:"name"`                             // 字段名称
	Title      string    `gorm:"column:title;type:varchar(255);not null;comment:字段提示文字" json:"title"`                         // 字段提示文字
	FormID     uint64    `gorm:"column:form_id;type:int;comment:表单id" json:"form_id"`                                         // 表单id
	Value      string    `gorm:"column:value;type:varchar(5000);comment:值" json:"value"`                                      // 值
	Status     uint64    `gorm:"column:status;type:tinyint(1);comment:是否隐藏" json:"status"`                                    // 是否隐藏
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// EbSystemConfigModel 新配置表 模型实例
func NewEbSystemConfigModel(db *gorm.DB) *EbSystemConfigModel {
	return &EbSystemConfigModel{DBModel: *model.NewDBModel(db, "crmeb", "eb_system_config")}
}
