// Code generated by gocli

package eb_article_model

import (
	"crmeb_go/internal/model"
	"gorm.io/gorm"
	"time"
)

// EbArticleModel 文章管理表 模型
type EbArticleModel struct {
	model.DBModel
	ID            uint64    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:文章管理ID" json:"id"`                   // 文章管理ID
	Cid           string    `gorm:"column:cid;type:varchar(255);not null;comment:分类id" json:"cid"`                                        // 分类id
	Title         string    `gorm:"column:title;type:varchar(255);not null;comment:文章标题" json:"title"`                                    // 文章标题
	Author        string    `gorm:"column:author;type:varchar(255);comment:文章作者" json:"author"`                                           // 文章作者
	ImageInput    string    `gorm:"column:image_input;type:varchar(255);not null;comment:文章图片" json:"image_input"`                        // 文章图片
	Synopsis      string    `gorm:"column:synopsis;type:varchar(255);comment:文章简介" json:"synopsis"`                                       // 文章简介
	ShareTitle    string    `gorm:"column:share_title;type:varchar(255);comment:文章分享标题" json:"share_title"`                               // 文章分享标题
	ShareSynopsis string    `gorm:"column:share_synopsis;type:varchar(255);comment:文章分享简介" json:"share_synopsis"`                         // 文章分享简介
	Visit         string    `gorm:"column:visit;type:varchar(255);comment:浏览次数" json:"visit"`                                             // 浏览次数
	Sort          uint64    `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                                        // 排序
	URL           string    `gorm:"column:url;type:varchar(255);comment:原文链接" json:"url"`                                                 // 原文链接
	MediaID       string    `gorm:"column:media_id;type:varchar(100);comment:微信素材id" json:"media_id"`                                     // 微信素材id
	Status        uint64    `gorm:"column:status;type:tinyint unsigned;not null;comment:状态" json:"status"`                                // 状态
	Hide          uint64    `gorm:"column:hide;type:tinyint unsigned;not null;comment:是否隐藏" json:"hide"`                                  // 是否隐藏
	AdminID       uint64    `gorm:"column:admin_id;type:int unsigned;not null;comment:管理员id" json:"admin_id"`                             // 管理员id
	MerID         uint64    `gorm:"column:mer_id;type:int unsigned;comment:商户id" json:"mer_id"`                                           // 商户id
	ProductID     uint64    `gorm:"column:product_id;type:int;not null;comment:商品关联id" json:"product_id"`                                 // 商品关联id
	IsHot         uint64    `gorm:"column:is_hot;type:tinyint unsigned;not null;comment:是否热门(小程序)" json:"is_hot"`                         // 是否热门(小程序)
	IsBanner      uint64    `gorm:"column:is_banner;type:tinyint unsigned;not null;comment:是否轮播图(小程序)" json:"is_banner"`                  // 是否轮播图(小程序)
	Content       string    `gorm:"column:content;type:text;not null;comment:文章内容" json:"content"`                                        // 文章内容
	CreateTime    time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// EbArticleModel 新文章管理表 模型实例
func NewEbArticleModel(db *gorm.DB) *EbArticleModel {
	return &EbArticleModel{DBModel: *model.NewDBModel(db, "crmeb", "eb_article")}
}
