// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameBrand = "brand"

// Brand 品牌表
type Brand struct {
	ID        int64                 `gorm:"column:id;type:int unsigned;primaryKey;comment:主键" json:"id"`                    // 主键
	Name      string                `gorm:"column:name;type:varchar(255);not null;comment:名称" json:"name"`                  // 名称
	Code      string                `gorm:"column:code;type:char(16);not null;comment:编码" json:"code"`                      // 编码
	Icon      string                `gorm:"column:icon;type:varchar(255);not null;comment:图标" json:"icon"`                  // 图标
	Sort      int64                 `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                  // 排序
	CreatedBy int64                 `gorm:"column:created_by;type:int unsigned;not null;comment:创建时间" json:"created_by"`    // 创建时间
	UpdatedBy int64                 `gorm:"column:updated_by;type:int unsigned;not null;comment:修改时间" json:"updated_by"`    // 修改时间
	CreatedAt int64                 `gorm:"column:created_at;type:bigint unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint unsigned;not null;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint unsigned;not null;comment:是否删除" json:"-"`         // 是否删除
}

// TableName Brand's table name
func (*Brand) TableName() string {
	return TableNameBrand
}
