// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbArticle = "eb_article"

// EbArticle 文章管理表
type EbArticle struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:文章管理ID" json:"id"`                      // 文章管理ID
	Cid           string    `gorm:"column:cid;not null;comment:分类id" json:"cid"`                                           // 分类id
	Title         string    `gorm:"column:title;not null;comment:文章标题" json:"title"`                                       // 文章标题
	Author        string    `gorm:"column:author;comment:文章作者" json:"author"`                                              // 文章作者
	ImageInput    string    `gorm:"column:image_input;not null;comment:文章图片" json:"image_input"`                           // 文章图片
	Synopsis      string    `gorm:"column:synopsis;comment:文章简介" json:"synopsis"`                                          // 文章简介
	ShareTitle    string    `gorm:"column:share_title;comment:文章分享标题" json:"share_title"`                                  // 文章分享标题
	ShareSynopsis string    `gorm:"column:share_synopsis;comment:文章分享简介" json:"share_synopsis"`                            // 文章分享简介
	Visit         string    `gorm:"column:visit;comment:浏览次数" json:"visit"`                                                // 浏览次数
	Sort          int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                                           // 排序
	URL           string    `gorm:"column:url;comment:原文链接" json:"url"`                                                    // 原文链接
	MediaID       string    `gorm:"column:media_id;comment:微信素材id" json:"media_id"`                                        // 微信素材id
	Status        int32     `gorm:"column:status;not null;comment:状态" json:"status"`                                       // 状态
	Hide          int32     `gorm:"column:hide;not null;comment:是否隐藏" json:"hide"`                                         // 是否隐藏
	AdminID       int32     `gorm:"column:admin_id;not null;comment:管理员id" json:"admin_id"`                                // 管理员id
	MerID         int32     `gorm:"column:mer_id;comment:商户id" json:"mer_id"`                                              // 商户id
	ProductID     int32     `gorm:"column:product_id;not null;comment:商品关联id" json:"product_id"`                           // 商品关联id
	IsHot         int32     `gorm:"column:is_hot;not null;comment:是否热门(小程序)" json:"is_hot"`                                // 是否热门(小程序)
	IsBanner      int32     `gorm:"column:is_banner;not null;comment:是否轮播图(小程序)" json:"is_banner"`                         // 是否轮播图(小程序)
	Content       string    `gorm:"column:content;not null;comment:文章内容" json:"content"`                                   // 文章内容
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbArticle's table name
func (*EbArticle) TableName() string {
	return TableNameEbArticle
}
