// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbCategory = "eb_category"

// EbCategory 分类表
type EbCategory struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid        int32     `gorm:"column:pid;not null;comment:父级ID" json:"pid"`                                                      // 父级ID
	Path       string    `gorm:"column:path;not null;default:/0/;comment:路径" json:"path"`                                          // 路径
	Name       string    `gorm:"column:name;not null;comment:分类名称" json:"name"`                                                    // 分类名称
	Type       int32     `gorm:"column:type;default:1;comment:类型，1 产品分类，2 附件分类，3 文章分类， 4 设置分类， 5 菜单分类，6 配置分类， 7 秒杀配置" json:"type"` // 类型，1 产品分类，2 附件分类，3 文章分类， 4 设置分类， 5 菜单分类，6 配置分类， 7 秒杀配置
	URL        string    `gorm:"column:url;comment:地址" json:"url"`                                                                 // 地址
	Extra      string    `gorm:"column:extra;comment:扩展字段 Jsos格式" json:"extra"`                                                    // 扩展字段 Jsos格式
	Status     bool      `gorm:"column:status;not null;default:1;comment:状态, 1正常，0失效" json:"status"`                               // 状态, 1正常，0失效
	Sort       int32     `gorm:"column:sort;not null;default:99999;comment:排序" json:"sort"`                                        // 排序
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`            // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`            // 更新时间
}

// TableName EbCategory's table name
func (*EbCategory) TableName() string {
	return TableNameEbCategory
}
