// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbExpress = "eb_express"

// EbExpress 快递公司表
type EbExpress struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:快递公司id" json:"id"` // 快递公司id
	Code       string `gorm:"column:code;not null;comment:快递公司简称" json:"code"`                  // 快递公司简称
	Name       string `gorm:"column:name;not null;comment:快递公司全称" json:"name"`                  // 快递公司全称
	PartnerID  bool   `gorm:"column:partner_id;not null;comment:是否需要月结账号" json:"partner_id"`    // 是否需要月结账号
	PartnerKey bool   `gorm:"column:partner_key;not null;comment:是否需要月结密码" json:"partner_key"`  // 是否需要月结密码
	Net        bool   `gorm:"column:net;not null;comment:是否需要取件网店" json:"net"`                  // 是否需要取件网店
	Account    string `gorm:"column:account;not null;comment:账号" json:"account"`                // 账号
	Password   string `gorm:"column:password;not null;comment:密码" json:"password"`              // 密码
	NetName    string `gorm:"column:net_name;not null;comment:网点名称" json:"net_name"`            // 网点名称
	Sort       int32  `gorm:"column:sort;not null;comment:排序" json:"sort"`                      // 排序
	IsShow     bool   `gorm:"column:is_show;not null;comment:是否显示" json:"is_show"`              // 是否显示
	Status     bool   `gorm:"column:status;not null;comment:是否可用" json:"status"`                // 是否可用
}

// TableName EbExpress's table name
func (*EbExpress) TableName() string {
	return TableNameEbExpress
}
