// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbShippingTemplatesFree = "eb_shipping_templates_free"

// EbShippingTemplatesFree 运费模板包邮
type EbShippingTemplatesFree struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:编号" json:"id"`                          // 编号
	TempID     int32     `gorm:"column:temp_id;not null;comment:模板ID" json:"temp_id"`                                   // 模板ID
	CityID     int32     `gorm:"column:city_id;not null;comment:城市ID" json:"city_id"`                                   // 城市ID
	Title      string    `gorm:"column:title;comment:描述" json:"title"`                                                  // 描述
	Number     float64   `gorm:"column:number;not null;default:0.00;comment:包邮件数" json:"number"`                        // 包邮件数
	Price      float64   `gorm:"column:price;not null;default:0.00;comment:包邮金额" json:"price"`                          // 包邮金额
	Type       bool      `gorm:"column:type;not null;default:1;comment:计费方式" json:"type"`                               // 计费方式
	Uniqid     string    `gorm:"column:uniqid;not null;comment:分组唯一值" json:"uniqid"`                                    // 分组唯一值
	Status     bool      `gorm:"column:status;comment:是否无效" json:"status"`                                              // 是否无效
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbShippingTemplatesFree's table name
func (*EbShippingTemplatesFree) TableName() string {
	return TableNameEbShippingTemplatesFree
}
