// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSmsTemplate = "eb_sms_template"

// EbSmsTemplate 短信模板表
type EbSmsTemplate struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	TempID     string    `gorm:"column:temp_id;not null;default:0;comment:短信模板id" json:"temp_id"`                       // 短信模板id
	TempType   int32     `gorm:"column:temp_type;not null;default:1;comment:模板类型" json:"temp_type"`                     // 模板类型
	Title      string    `gorm:"column:title;not null;comment:模板说明" json:"title"`                                       // 模板说明
	Type       string    `gorm:"column:type;not null;comment:类型" json:"type"`                                           // 类型
	TempKey    string    `gorm:"column:temp_key;not null;comment:模板编号" json:"temp_key"`                                 // 模板编号
	Status     int32     `gorm:"column:status;not null;default:1;comment:状态" json:"status"`                             // 状态
	Content    string    `gorm:"column:content;not null;comment:短息内容" json:"content"`                                   // 短息内容
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"` // 添加时间
}

// TableName EbSmsTemplate's table name
func (*EbSmsTemplate) TableName() string {
	return TableNameEbSmsTemplate
}
