// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemConfig = "eb_system_config"

// EbSystemConfig 配置表
type EbSystemConfig struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:配置id" json:"id"`               // 配置id
	Name       string    `gorm:"column:name;not null;comment:字段名称" json:"name"`                                // 字段名称
	Title      string    `gorm:"column:title;not null;comment:字段提示文字" json:"title"`                            // 字段提示文字
	FormID     int32     `gorm:"column:form_id;comment:表单id" json:"form_id"`                                   // 表单id
	Value      string    `gorm:"column:value;comment:值" json:"value"`                                          // 值
	Status     bool      `gorm:"column:status;comment:是否隐藏" json:"status"`                                     // 是否隐藏
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemConfig's table name
func (*EbSystemConfig) TableName() string {
	return TableNameEbSystemConfig
}
