// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStorePink = "eb_store_pink"

// EbStorePink 拼团表
type EbStorePink struct {
	ID         int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:拼团ID" json:"id"`        // 拼团ID
	UID        int32   `gorm:"column:uid;not null;comment:用户id" json:"uid"`                           // 用户id
	OrderID    string  `gorm:"column:order_id;not null;comment:订单id 生成" json:"order_id"`              // 订单id 生成
	OrderIDKey int32   `gorm:"column:order_id_key;not null;comment:订单id  数据库" json:"order_id_key"`    // 订单id  数据库
	TotalNum   int32   `gorm:"column:total_num;not null;comment:购买商品个数" json:"total_num"`             // 购买商品个数
	TotalPrice float64 `gorm:"column:total_price;not null;comment:购买总金额" json:"total_price"`          // 购买总金额
	Cid        int32   `gorm:"column:cid;not null;comment:拼团商品id" json:"cid"`                         // 拼团商品id
	Pid        int32   `gorm:"column:pid;not null;comment:商品id" json:"pid"`                           // 商品id
	People     int32   `gorm:"column:people;not null;comment:拼图总人数" json:"people"`                    // 拼图总人数
	Price      float64 `gorm:"column:price;not null;comment:拼团商品单价" json:"price"`                     // 拼团商品单价
	AddTime    int64   `gorm:"column:add_time;not null;comment:开始时间" json:"add_time"`                 // 开始时间
	StopTime   int64   `gorm:"column:stop_time;not null;comment:结束时间" json:"stop_time"`               // 结束时间
	KID        int32   `gorm:"column:k_id;not null;comment:团长id 0为团长" json:"k_id"`                    // 团长id 0为团长
	IsTpl      int32   `gorm:"column:is_tpl;not null;comment:是否发送模板消息0未发送1已发送" json:"is_tpl"`         // 是否发送模板消息0未发送1已发送
	IsRefund   int32   `gorm:"column:is_refund;not null;comment:是否退款 0未退款 1已退款" json:"is_refund"`     // 是否退款 0未退款 1已退款
	Status     int32   `gorm:"column:status;not null;default:1;comment:状态1进行中2已完成3未完成" json:"status"` // 状态1进行中2已完成3未完成
	IsVirtual  bool    `gorm:"column:is_virtual;not null;comment:是否虚拟拼团" json:"is_virtual"`           // 是否虚拟拼团
	Nickname   string  `gorm:"column:nickname;not null;comment:用户昵称" json:"nickname"`                 // 用户昵称
	Avatar     string  `gorm:"column:avatar;not null;comment:用户头像" json:"avatar"`                     // 用户头像
}

// TableName EbStorePink's table name
func (*EbStorePink) TableName() string {
	return TableNameEbStorePink
}
