// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemRole = "eb_system_role"

// EbSystemRole 身份管理表
type EbSystemRole struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:身份管理id" json:"id"` // 身份管理id
	RoleName   string    `gorm:"column:role_name;not null;comment:身份管理名称" json:"role_name"`        // 身份管理名称
	Rules      string    `gorm:"column:rules;not null;comment:身份管理权限(menus_id)" json:"rules"`      // 身份管理权限(menus_id)
	Level      int32     `gorm:"column:level;not null" json:"level"`
	Status     int32     `gorm:"column:status;not null;default:1;comment:状态" json:"status"`                             // 状态
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemRole's table name
func (*EbSystemRole) TableName() string {
	return TableNameEbSystemRole
}
