// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemCity = "eb_system_city"

// EbSystemCity 城市表
type EbSystemCity struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	CityID     int32     `gorm:"column:city_id;not null;comment:城市id" json:"city_id"`                                   // 城市id
	Level      int32     `gorm:"column:level;not null;comment:省市级别" json:"level"`                                       // 省市级别
	ParentID   int32     `gorm:"column:parent_id;not null;comment:父级id" json:"parent_id"`                               // 父级id
	AreaCode   string    `gorm:"column:area_code;not null;comment:区号" json:"area_code"`                                 // 区号
	Name       string    `gorm:"column:name;not null;comment:名称" json:"name"`                                           // 名称
	MergerName string    `gorm:"column:merger_name;not null;comment:合并名称" json:"merger_name"`                           // 合并名称
	Lng        string    `gorm:"column:lng;not null;comment:经度" json:"lng"`                                             // 经度
	Lat        string    `gorm:"column:lat;not null;comment:纬度" json:"lat"`                                             // 纬度
	IsShow     bool      `gorm:"column:is_show;not null;default:1;comment:是否展示" json:"is_show"`                         // 是否展示
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemCity's table name
func (*EbSystemCity) TableName() string {
	return TableNameEbSystemCity
}
