// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreCouponUser = "eb_store_coupon_user"

// EbStoreCouponUser 优惠券记录表
type EbStoreCouponUser struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                  // id
	CouponID   int32     `gorm:"column:coupon_id;not null;comment:优惠券发布id" json:"coupon_id"`                    // 优惠券发布id
	Cid        int32     `gorm:"column:cid;not null;comment:兑换的项目id" json:"cid"`                                // 兑换的项目id
	UID        int32     `gorm:"column:uid;not null;comment:领取人id" json:"uid"`                                  // 领取人id
	Name       string    `gorm:"column:name;not null;comment:优惠券名称" json:"name"`                                // 优惠券名称
	Money      float64   `gorm:"column:money;not null;default:0.00;comment:优惠券的面值" json:"money"`                // 优惠券的面值
	MinPrice   float64   `gorm:"column:min_price;not null;default:0.00;comment:最低消费多少金额可用优惠券" json:"min_price"` // 最低消费多少金额可用优惠券
	Type       string    `gorm:"column:type;not null;default:send;comment:获取方式，send后台发放, 用户领取 get" json:"type"` // 获取方式，send后台发放, 用户领取 get
	Status     bool      `gorm:"column:status;not null;comment:状态（0：未使用，1：已使用, 2:已失效）" json:"status"`           // 状态（0：未使用，1：已使用, 2:已失效）
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`  // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`  // 更新时间
	StartTime  time.Time `gorm:"column:start_time;comment:开始使用时间" json:"start_time"`                            // 开始使用时间
	EndTime    time.Time `gorm:"column:end_time;comment:过期时间" json:"end_time"`                                  // 过期时间
	UseTime    time.Time `gorm:"column:use_time;comment:使用时间" json:"use_time"`                                  // 使用时间
	UseType    bool      `gorm:"column:use_type;default:1;comment:使用类型 1 全场通用, 2 商品券, 3 品类券" json:"use_type"`   // 使用类型 1 全场通用, 2 商品券, 3 品类券
	PrimaryKey string    `gorm:"column:primary_key;comment:所属商品id / 分类id" json:"primary_key"`                   // 所属商品id / 分类id
}

// TableName EbStoreCouponUser's table name
func (*EbStoreCouponUser) TableName() string {
	return TableNameEbStoreCouponUser
}
