// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreBargain = "eb_store_bargain"

// EbStoreBargain 砍价表
type EbStoreBargain struct {
	ID              int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:砍价商品ID" json:"id"`                          // 砍价商品ID
	ProductID       int32   `gorm:"column:product_id;not null;comment:关联商品ID" json:"product_id"`                               // 关联商品ID
	Title           string  `gorm:"column:title;not null;comment:砍价活动名称" json:"title"`                                         // 砍价活动名称
	Image           string  `gorm:"column:image;not null;comment:砍价活动图片" json:"image"`                                         // 砍价活动图片
	UnitName        string  `gorm:"column:unit_name;comment:单位名称" json:"unit_name"`                                            // 单位名称
	Stock           int32   `gorm:"column:stock;comment:库存" json:"stock"`                                                      // 库存
	Sales           int32   `gorm:"column:sales;comment:销量" json:"sales"`                                                      // 销量
	Images          string  `gorm:"column:images;not null;comment:砍价商品轮播图" json:"images"`                                      // 砍价商品轮播图
	StartTime       int64   `gorm:"column:start_time;not null;comment:砍价开启时间" json:"start_time"`                               // 砍价开启时间
	StopTime        int64   `gorm:"column:stop_time;not null;comment:砍价结束时间" json:"stop_time"`                                 // 砍价结束时间
	StoreName       string  `gorm:"column:store_name;comment:砍价商品名称" json:"store_name"`                                        // 砍价商品名称
	Price           float64 `gorm:"column:price;comment:砍价金额" json:"price"`                                                    // 砍价金额
	MinPrice        float64 `gorm:"column:min_price;comment:砍价商品最低价" json:"min_price"`                                         // 砍价商品最低价
	Num             int32   `gorm:"column:num;comment:购买数量限制——单个活动每个用户发起砍价次数限制" json:"num"`                                    // 购买数量限制——单个活动每个用户发起砍价次数限制
	BargainMaxPrice float64 `gorm:"column:bargain_max_price;comment:用户每次砍价的最大金额" json:"bargain_max_price"`                     // 用户每次砍价的最大金额
	BargainMinPrice float64 `gorm:"column:bargain_min_price;comment:用户每次砍价的最小金额" json:"bargain_min_price"`                     // 用户每次砍价的最小金额
	BargainNum      int32   `gorm:"column:bargain_num;not null;default:1;comment:帮砍次数——单个商品用户可以帮砍的次数" json:"bargain_num"`      // 帮砍次数——单个商品用户可以帮砍的次数
	Status          int32   `gorm:"column:status;not null;default:1;comment:砍价状态 0(到砍价时间不自动开启)  1(到砍价时间自动开启时间)" json:"status"` // 砍价状态 0(到砍价时间不自动开启)  1(到砍价时间自动开启时间)
	GiveIntegral    int32   `gorm:"column:give_integral;comment:反多少积分" json:"give_integral"`                                   // 反多少积分
	Info            string  `gorm:"column:info;comment:砍价活动简介" json:"info"`                                                    // 砍价活动简介
	Cost            float64 `gorm:"column:cost;comment:成本价" json:"cost"`                                                       // 成本价
	Sort            int32   `gorm:"column:sort;not null;comment:排序" json:"sort"`                                               // 排序
	IsHot           int32   `gorm:"column:is_hot;not null;comment:是否推荐0不推荐1推荐" json:"is_hot"`                                  // 是否推荐0不推荐1推荐
	IsDel           int32   `gorm:"column:is_del;not null;comment:是否删除 0未删除 1删除" json:"is_del"`                                // 是否删除 0未删除 1删除
	AddTime         int64   `gorm:"column:add_time;comment:添加时间" json:"add_time"`                                              // 添加时间
	IsPostage       int32   `gorm:"column:is_postage;not null;default:1;comment:是否包邮 0不包邮 1包邮" json:"is_postage"`              // 是否包邮 0不包邮 1包邮
	Postage         float64 `gorm:"column:postage;comment:邮费" json:"postage"`                                                  // 邮费
	Rule            string  `gorm:"column:rule;comment:砍价规则" json:"rule"`                                                      // 砍价规则
	Look            int32   `gorm:"column:look;comment:砍价商品浏览量" json:"look"`                                                   // 砍价商品浏览量
	Share           int32   `gorm:"column:share;comment:砍价商品分享量" json:"share"`                                                 // 砍价商品分享量
	TempID          int32   `gorm:"column:temp_id;comment:运费模板ID" json:"temp_id"`                                              // 运费模板ID
	Weight          float64 `gorm:"column:weight;default:0.00;comment:重量" json:"weight"`                                       // 重量
	Volume          float64 `gorm:"column:volume;default:0.00;comment:体积" json:"volume"`                                       // 体积
	Quota           int32   `gorm:"column:quota;not null;comment:限购总数" json:"quota"`                                           // 限购总数
	QuotaShow       int32   `gorm:"column:quota_show;not null;comment:限量总数显示" json:"quota_show"`                               // 限量总数显示
	PeopleNum       int32   `gorm:"column:people_num;comment:砍价人数——需要多少人砍价成功" json:"people_num"`                               // 砍价人数——需要多少人砍价成功
}

// TableName EbStoreBargain's table name
func (*EbStoreBargain) TableName() string {
	return TableNameEbStoreBargain
}
