// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemGroup = "eb_system_group"

// EbSystemGroup 组合数据表
type EbSystemGroup struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:组合数据ID" json:"id"`             // 组合数据ID
	Name       string    `gorm:"column:name;not null;comment:数据组名称" json:"name"`                               // 数据组名称
	Info       string    `gorm:"column:info;not null;comment:简介" json:"info"`                                  // 简介
	FormID     int32     `gorm:"column:form_id;not null;comment:form 表单 id" json:"form_id"`                    // form 表单 id
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemGroup's table name
func (*EbSystemGroup) TableName() string {
	return TableNameEbSystemGroup
}
