// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbShippingTemplate = "eb_shipping_templates"

// EbShippingTemplate 运费模板
type EbShippingTemplate struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:编号" json:"id"`                          // 编号
	Name       string    `gorm:"column:name;not null;comment:模板名称" json:"name"`                                         // 模板名称
	Type       bool      `gorm:"column:type;not null;default:1;comment:计费方式" json:"type"`                               // 计费方式
	Appoint    bool      `gorm:"column:appoint;not null;comment:指定包邮" json:"appoint"`                                   // 指定包邮
	Sort       int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                                           // 排序
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbShippingTemplate's table name
func (*EbShippingTemplate) TableName() string {
	return TableNameEbShippingTemplate
}
