// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbSystemRoleMenu = "eb_system_role_menu"

// EbSystemRoleMenu 角色菜单关联表
type EbSystemRoleMenu struct {
	Rid    int32 `gorm:"column:rid;primaryKey;comment:角色id" json:"rid"`         // 角色id
	MenuID int32 `gorm:"column:menu_id;primaryKey;comment:权限id" json:"menu_id"` // 权限id
}

// TableName EbSystemRoleMenu's table name
func (*EbSystemRoleMenu) TableName() string {
	return TableNameEbSystemRoleMenu
}
