// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemMenu = "eb_system_menu"

// EbSystemMenu 系统菜单表
type EbSystemMenu struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid        int32     `gorm:"column:pid;not null;comment:父级ID" json:"pid"`                                           // 父级ID
	Name       string    `gorm:"column:name;comment:名称" json:"name"`                                                    // 名称
	Icon       string    `gorm:"column:icon;comment:icon" json:"icon"`                                                  // icon
	Perms      string    `gorm:"column:perms;comment:权限标识" json:"perms"`                                                // 权限标识
	Component  string    `gorm:"column:component;comment:组件路径" json:"component"`                                        // 组件路径
	MenuType   string    `gorm:"column:menu_type;default:M;comment:类型，M-目录，C-菜单，A-按钮" json:"menu_type"`                 // 类型，M-目录，C-菜单，A-按钮
	Sort       int32     `gorm:"column:sort;not null;default:99999;comment:排序" json:"sort"`                             // 排序
	IsShow     bool      `gorm:"column:is_show;not null;default:1;comment:显示状态" json:"is_show"`                         // 显示状态
	IsDelte    int32     `gorm:"column:is_delte;comment:是否删除" json:"is_delte"`                                          // 是否删除
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemMenu's table name
func (*EbSystemMenu) TableName() string {
	return TableNameEbSystemMenu
}
