// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreSeckillManger = "eb_store_seckill_manger"

// EbStoreSeckillManger mapped from table <eb_store_seckill_manger>
type EbStoreSeckillManger struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;comment:秒杀名称" json:"name"`                                         // 秒杀名称
	StartTime  int32     `gorm:"column:start_time;comment:秒杀开始时间段" json:"start_time"`                          // 秒杀开始时间段
	EndTime    int32     `gorm:"column:end_time;comment:秒杀结束时间段" json:"end_time"`                              // 秒杀结束时间段
	Img        string    `gorm:"column:img;comment:主图" json:"img"`                                             // 主图
	SilderImgs string    `gorm:"column:silder_imgs;comment:轮播图" json:"silder_imgs"`                            // 轮播图
	Sort       int32     `gorm:"column:sort;comment:排序" json:"sort"`                                           // 排序
	Status     int32     `gorm:"column:status;comment:状态 0=关闭 1=开启" json:"status"`                             // 状态 0=关闭 1=开启
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                           // 更新时间
	IsDel      int32     `gorm:"column:is_del;not null;comment:删除标记 0=为删除 1=删除" json:"is_del"`                 // 删除标记 0=为删除 1=删除
}

// TableName EbStoreSeckillManger's table name
func (*EbStoreSeckillManger) TableName() string {
	return TableNameEbStoreSeckillManger
}
