// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreBargainUserHelp = "eb_store_bargain_user_help"

// EbStoreBargainUserHelp 砍价用户帮助表
type EbStoreBargainUserHelp struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:砍价用户帮助表ID" json:"id"` // 砍价用户帮助表ID
	UID           int32   `gorm:"column:uid;comment:帮助的用户id" json:"uid"`                               // 帮助的用户id
	BargainID     int32   `gorm:"column:bargain_id;comment:砍价商品ID" json:"bargain_id"`                  // 砍价商品ID
	BargainUserID int32   `gorm:"column:bargain_user_id;comment:用户参与砍价表id" json:"bargain_user_id"`     // 用户参与砍价表id
	Price         float64 `gorm:"column:price;comment:帮助砍价多少金额" json:"price"`                          // 帮助砍价多少金额
	AddTime       int64   `gorm:"column:add_time;comment:添加时间" json:"add_time"`                        // 添加时间
}

// TableName EbStoreBargainUserHelp's table name
func (*EbStoreBargainUserHelp) TableName() string {
	return TableNameEbStoreBargainUserHelp
}
