// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProduct = "eb_store_product"

// EbStoreProduct 商品表
type EbStoreProduct struct {
	ID           int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:商品id" json:"id"`              // 商品id
	MerID        int32   `gorm:"column:mer_id;not null;comment:商户Id(0为总后台管理员创建,不为0的时候是商户后台创建)" json:"mer_id"` // 商户Id(0为总后台管理员创建,不为0的时候是商户后台创建)
	Image        string  `gorm:"column:image;not null;comment:商品图片" json:"image"`                             // 商品图片
	SliderImage  string  `gorm:"column:slider_image;not null;comment:轮播图" json:"slider_image"`                // 轮播图
	StoreName    string  `gorm:"column:store_name;not null;comment:商品名称" json:"store_name"`                   // 商品名称
	StoreInfo    string  `gorm:"column:store_info;not null;comment:商品简介" json:"store_info"`                   // 商品简介
	Keyword      string  `gorm:"column:keyword;not null;comment:关键字" json:"keyword"`                          // 关键字
	BarCode      string  `gorm:"column:bar_code;not null;comment:商品条码（一维码）" json:"bar_code"`                  // 商品条码（一维码）
	CateID       string  `gorm:"column:cate_id;not null;comment:分类id" json:"cate_id"`                         // 分类id
	Price        float64 `gorm:"column:price;not null;default:0.00;comment:商品价格" json:"price"`                // 商品价格
	VipPrice     float64 `gorm:"column:vip_price;not null;default:0.00;comment:会员价格" json:"vip_price"`        // 会员价格
	OtPrice      float64 `gorm:"column:ot_price;not null;default:0.00;comment:市场价" json:"ot_price"`           // 市场价
	Postage      float64 `gorm:"column:postage;not null;default:0.00;comment:邮费" json:"postage"`              // 邮费
	UnitName     string  `gorm:"column:unit_name;not null;comment:单位名" json:"unit_name"`                      // 单位名
	Sort         int32   `gorm:"column:sort;not null;comment:排序" json:"sort"`                                 // 排序
	Sales        int32   `gorm:"column:sales;not null;comment:销量" json:"sales"`                               // 销量
	Stock        int32   `gorm:"column:stock;not null;comment:库存" json:"stock"`                               // 库存
	IsShow       bool    `gorm:"column:is_show;not null;default:1;comment:状态（0：未上架，1：上架）" json:"is_show"`     // 状态（0：未上架，1：上架）
	IsHot        bool    `gorm:"column:is_hot;not null;comment:是否热卖" json:"is_hot"`                           // 是否热卖
	IsBenefit    bool    `gorm:"column:is_benefit;not null;comment:是否优惠" json:"is_benefit"`                   // 是否优惠
	IsBest       bool    `gorm:"column:is_best;not null;comment:是否精品" json:"is_best"`                         // 是否精品
	IsNew        bool    `gorm:"column:is_new;not null;comment:是否新品" json:"is_new"`                           // 是否新品
	AddTime      int32   `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`                       // 添加时间
	IsPostage    int32   `gorm:"column:is_postage;not null;comment:是否包邮" json:"is_postage"`                   // 是否包邮
	IsDel        int32   `gorm:"column:is_del;not null;comment:是否删除" json:"is_del"`                           // 是否删除
	MerUse       int32   `gorm:"column:mer_use;not null;comment:商户是否代理 0不可代理1可代理" json:"mer_use"`             // 商户是否代理 0不可代理1可代理
	GiveIntegral int32   `gorm:"column:give_integral;comment:获得积分" json:"give_integral"`                      // 获得积分
	Cost         float64 `gorm:"column:cost;not null;default:0.00;comment:成本价" json:"cost"`                   // 成本价
	IsSeckill    int32   `gorm:"column:is_seckill;not null;comment:秒杀状态 0 未开启 1已开启" json:"is_seckill"`        // 秒杀状态 0 未开启 1已开启
	IsBargain    int32   `gorm:"column:is_bargain;comment:砍价状态 0未开启 1开启" json:"is_bargain"`                   // 砍价状态 0未开启 1开启
	IsGood       bool    `gorm:"column:is_good;not null;comment:是否优品推荐" json:"is_good"`                       // 是否优品推荐
	IsSub        bool    `gorm:"column:is_sub;not null;comment:是否单独分佣" json:"is_sub"`                         // 是否单独分佣
	Ficti        int32   `gorm:"column:ficti;default:100;comment:虚拟销量" json:"ficti"`                          // 虚拟销量
	Browse       int32   `gorm:"column:browse;comment:浏览量" json:"browse"`                                     // 浏览量
	CodePath     string  `gorm:"column:code_path;not null;comment:商品二维码地址(用户小程序海报)" json:"code_path"`         // 商品二维码地址(用户小程序海报)
	SoureLink    string  `gorm:"column:soure_link;comment:淘宝京东1688类型" json:"soure_link"`                      // 淘宝京东1688类型
	VideoLink    string  `gorm:"column:video_link;not null;comment:主图视频链接" json:"video_link"`                 // 主图视频链接
	TempID       int32   `gorm:"column:temp_id;not null;default:1;comment:运费模板ID" json:"temp_id"`             // 运费模板ID
	SpecType     bool    `gorm:"column:spec_type;not null;comment:规格 0单 1多" json:"spec_type"`                 // 规格 0单 1多
	Activity     string  `gorm:"column:activity;not null;comment:活动显示排序0=默认, 1=秒杀，2=砍价，3=拼团" json:"activity"` // 活动显示排序0=默认, 1=秒杀，2=砍价，3=拼团
	FlatPattern  string  `gorm:"column:flat_pattern;not null;comment:展示图" json:"flat_pattern"`                // 展示图
	IsRecycle    bool    `gorm:"column:is_recycle;not null;comment:是否回收站" json:"is_recycle"`                  // 是否回收站
}

// TableName EbStoreProduct's table name
func (*EbStoreProduct) TableName() string {
	return TableNameEbStoreProduct
}
