// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreOrderStatus = "eb_store_order_status"

// EbStoreOrderStatus 订单操作记录表
type EbStoreOrderStatus struct {
	Oid           int32     `gorm:"column:oid;not null;comment:订单id" json:"oid"`                                           // 订单id
	ChangeType    string    `gorm:"column:change_type;not null;comment:操作类型" json:"change_type"`                           // 操作类型
	ChangeMessage string    `gorm:"column:change_message;not null;comment:操作备注" json:"change_message"`                     // 操作备注
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:操作时间" json:"create_time"` // 操作时间
}

// TableName EbStoreOrderStatus's table name
func (*EbStoreOrderStatus) TableName() string {
	return TableNameEbStoreOrderStatus
}
