// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreOrder = "eb_store_order"

// EbStoreOrder 订单表
type EbStoreOrder struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:订单ID" json:"id"`                     // 订单ID
	OrderID                string    `gorm:"column:order_id;not null;comment:订单号" json:"order_id"`                               // 订单号
	UID                    int32     `gorm:"column:uid;not null;comment:用户id" json:"uid"`                                        // 用户id
	RealName               string    `gorm:"column:real_name;not null;comment:用户姓名" json:"real_name"`                            // 用户姓名
	UserPhone              string    `gorm:"column:user_phone;not null;comment:用户电话" json:"user_phone"`                          // 用户电话
	UserAddress            string    `gorm:"column:user_address;not null;comment:详细地址" json:"user_address"`                      // 详细地址
	FreightPrice           float64   `gorm:"column:freight_price;not null;default:0.00;comment:运费金额" json:"freight_price"`       // 运费金额
	TotalNum               int32     `gorm:"column:total_num;not null;comment:订单商品总数" json:"total_num"`                          // 订单商品总数
	TotalPrice             float64   `gorm:"column:total_price;not null;default:0.00;comment:订单总价" json:"total_price"`           // 订单总价
	TotalPostage           float64   `gorm:"column:total_postage;not null;default:0.00;comment:邮费" json:"total_postage"`         // 邮费
	PayPrice               float64   `gorm:"column:pay_price;not null;default:0.00;comment:实际支付金额" json:"pay_price"`             // 实际支付金额
	PayPostage             float64   `gorm:"column:pay_postage;not null;default:0.00;comment:支付邮费" json:"pay_postage"`           // 支付邮费
	DeductionPrice         float64   `gorm:"column:deduction_price;not null;default:0.00;comment:抵扣金额" json:"deduction_price"`   // 抵扣金额
	CouponID               int32     `gorm:"column:coupon_id;not null;comment:优惠券id" json:"coupon_id"`                           // 优惠券id
	CouponPrice            float64   `gorm:"column:coupon_price;not null;default:0.00;comment:优惠券金额" json:"coupon_price"`        // 优惠券金额
	Paid                   int32     `gorm:"column:paid;not null;comment:支付状态" json:"paid"`                                      // 支付状态
	PayTime                time.Time `gorm:"column:pay_time;comment:支付时间" json:"pay_time"`                                       // 支付时间
	PayType                string    `gorm:"column:pay_type;not null;comment:支付方式" json:"pay_type"`                              // 支付方式
	CreateTime             time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`       // 创建时间
	Status                 bool      `gorm:"column:status;not null;comment:订单状态（0：待发货；1：待收货；2：已收货，待评价；3：已完成；）" json:"status"`    // 订单状态（0：待发货；1：待收货；2：已收货，待评价；3：已完成；）
	RefundStatus           int32     `gorm:"column:refund_status;not null;comment:0 未退款 1 申请中 2 已退款 3 退款中" json:"refund_status"` // 0 未退款 1 申请中 2 已退款 3 退款中
	RefundReasonWapImg     string    `gorm:"column:refund_reason_wap_img;comment:退款图片" json:"refund_reason_wap_img"`             // 退款图片
	RefundReasonWapExplain string    `gorm:"column:refund_reason_wap_explain;comment:退款用户说明" json:"refund_reason_wap_explain"`   // 退款用户说明
	RefundReasonWap        string    `gorm:"column:refund_reason_wap;comment:前台退款原因" json:"refund_reason_wap"`                   // 前台退款原因
	RefundReason           string    `gorm:"column:refund_reason;comment:不退款的理由" json:"refund_reason"`                           // 不退款的理由
	RefundReasonTime       time.Time `gorm:"column:refund_reason_time;comment:退款时间" json:"refund_reason_time"`                   // 退款时间
	RefundPrice            float64   `gorm:"column:refund_price;not null;default:0.00;comment:退款金额" json:"refund_price"`         // 退款金额
	DeliveryName           string    `gorm:"column:delivery_name;comment:快递名称/送货人姓名" json:"delivery_name"`                       // 快递名称/送货人姓名
	DeliveryType           string    `gorm:"column:delivery_type;comment:发货类型" json:"delivery_type"`                             // 发货类型
	DeliveryID             string    `gorm:"column:delivery_id;comment:快递单号/手机号" json:"delivery_id"`                             // 快递单号/手机号
	GainIntegral           int32     `gorm:"column:gain_integral;comment:消费赚取积分" json:"gain_integral"`                           // 消费赚取积分
	UseIntegral            int32     `gorm:"column:use_integral;comment:使用积分" json:"use_integral"`                               // 使用积分
	BackIntegral           int32     `gorm:"column:back_integral;comment:给用户退了多少积分" json:"back_integral"`                        // 给用户退了多少积分
	Mark                   string    `gorm:"column:mark;not null;comment:备注" json:"mark"`                                        // 备注
	IsDel                  int32     `gorm:"column:is_del;not null;comment:是否删除" json:"is_del"`                                  // 是否删除
	Remark                 string    `gorm:"column:remark;comment:管理员备注" json:"remark"`                                          // 管理员备注
	MerID                  int32     `gorm:"column:mer_id;not null;comment:商户ID" json:"mer_id"`                                  // 商户ID
	IsMerCheck             int32     `gorm:"column:is_mer_check;not null" json:"is_mer_check"`
	CombinationID          int32     `gorm:"column:combination_id;comment:拼团商品id0一般商品" json:"combination_id"`                        // 拼团商品id0一般商品
	PinkID                 int32     `gorm:"column:pink_id;not null;comment:拼团id 0没有拼团" json:"pink_id"`                              // 拼团id 0没有拼团
	Cost                   float64   `gorm:"column:cost;not null;comment:成本价" json:"cost"`                                           // 成本价
	SeckillID              int32     `gorm:"column:seckill_id;not null;comment:秒杀商品ID" json:"seckill_id"`                            // 秒杀商品ID
	BargainID              int32     `gorm:"column:bargain_id;comment:砍价id" json:"bargain_id"`                                       // 砍价id
	VerifyCode             string    `gorm:"column:verify_code;not null;comment:核销码" json:"verify_code"`                             // 核销码
	StoreID                int32     `gorm:"column:store_id;not null;comment:门店id" json:"store_id"`                                  // 门店id
	ShippingType           bool      `gorm:"column:shipping_type;not null;default:1;comment:配送方式 1=快递 ，2=门店自提" json:"shipping_type"` // 配送方式 1=快递 ，2=门店自提
	ClerkID                int32     `gorm:"column:clerk_id;not null;comment:店员id/核销员id" json:"clerk_id"`                            // 店员id/核销员id
	IsChannel              int32     `gorm:"column:is_channel;comment:支付渠道(0微信公众号1微信小程序2余额)" json:"is_channel"`                      // 支付渠道(0微信公众号1微信小程序2余额)
	IsRemind               int32     `gorm:"column:is_remind;comment:消息提醒" json:"is_remind"`                                         // 消息提醒
	IsSystemDel            bool      `gorm:"column:is_system_del;comment:后台是否删除" json:"is_system_del"`                               // 后台是否删除
	UpdateTime             time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`  // 更新时间
	DeliveryCode           string    `gorm:"column:delivery_code;comment:快递公司简称" json:"delivery_code"`                               // 快递公司简称
	BargainUserID          int32     `gorm:"column:bargain_user_id;not null;comment:用户拼团活动id 0没有" json:"bargain_user_id"`            // 用户拼团活动id 0没有
	Type                   int32     `gorm:"column:type;not null;comment:订单类型:0-普通订单，1-视频号订单" json:"type"`                           // 订单类型:0-普通订单，1-视频号订单
	ProTotalPrice          float64   `gorm:"column:pro_total_price;not null;default:0.00;comment:商品总价" json:"pro_total_price"`       // 商品总价
	BeforePayPrice         float64   `gorm:"column:before_pay_price;not null;default:0.00;comment:改价前支付金额" json:"before_pay_price"`  // 改价前支付金额
	IsAlterPrice           bool      `gorm:"column:is_alter_price;not null;comment:是否改价,0-否，1-是" json:"is_alter_price"`              // 是否改价,0-否，1-是
	OutTradeNo             string    `gorm:"column:out_trade_no;comment:商户系统内部的订单号,32个字符内、可包含字母, 其他说明见商户订单号" json:"out_trade_no"`    // 商户系统内部的订单号,32个字符内、可包含字母, 其他说明见商户订单号
}

// TableName EbStoreOrder's table name
func (*EbStoreOrder) TableName() string {
	return TableNameEbStoreOrder
}
