// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreProductRelation = "eb_store_product_relation"

// EbStoreProductRelation 商品点赞和收藏表
type EbStoreProductRelation struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                 // id
	UID        int32     `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                                  // 用户ID
	ProductID  int32     `gorm:"column:product_id;not null;comment:商品ID" json:"product_id"`                    // 商品ID
	Type       string    `gorm:"column:type;not null;comment:类型(收藏(collect）、点赞(like))" json:"type"`            // 类型(收藏(collect）、点赞(like))
	Category   string    `gorm:"column:category;not null;comment:某种类型的商品(普通商品、秒杀商品)" json:"category"`          // 某种类型的商品(普通商品、秒杀商品)
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbStoreProductRelation's table name
func (*EbStoreProductRelation) TableName() string {
	return TableNameEbStoreProductRelation
}
