// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreCombination = "eb_store_combination"

// EbStoreCombination 拼团商品表
type EbStoreCombination struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:拼团商品ID" json:"id"` // 拼团商品ID
	ProductID     int32   `gorm:"column:product_id;not null;comment:商品id" json:"product_id"`        // 商品id
	MerID         int32   `gorm:"column:mer_id;comment:商户id" json:"mer_id"`                         // 商户id
	Image         string  `gorm:"column:image;not null;comment:推荐图" json:"image"`                   // 推荐图
	Images        string  `gorm:"column:images;not null;comment:轮播图" json:"images"`                 // 轮播图
	Title         string  `gorm:"column:title;not null;comment:活动标题" json:"title"`                  // 活动标题
	Attr          string  `gorm:"column:attr;comment:活动属性" json:"attr"`                             // 活动属性
	People        int32   `gorm:"column:people;not null;comment:参团人数" json:"people"`                // 参团人数
	Info          string  `gorm:"column:info;not null;comment:简介" json:"info"`                      // 简介
	Price         float64 `gorm:"column:price;not null;comment:价格" json:"price"`                    // 价格
	Sort          int32   `gorm:"column:sort;not null;comment:排序" json:"sort"`                      // 排序
	Sales         int32   `gorm:"column:sales;not null;comment:销量" json:"sales"`                    // 销量
	Stock         int32   `gorm:"column:stock;not null;comment:库存" json:"stock"`                    // 库存
	AddTime       int64   `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`            // 添加时间
	IsHost        int32   `gorm:"column:is_host;not null;comment:推荐" json:"is_host"`                // 推荐
	IsShow        int32   `gorm:"column:is_show;not null;comment:商品状态" json:"is_show"`              // 商品状态
	IsDel         int32   `gorm:"column:is_del;not null" json:"is_del"`
	Combination   int32   `gorm:"column:combination;default:1" json:"combination"`
	MerUse        int32   `gorm:"column:mer_use;comment:商户是否可用1可用0不可用" json:"mer_use"`                              // 商户是否可用1可用0不可用
	IsPostage     int32   `gorm:"column:is_postage;comment:是否包邮1是0否" json:"is_postage"`                             // 是否包邮1是0否
	Postage       float64 `gorm:"column:postage;comment:邮费" json:"postage"`                                         // 邮费
	StartTime     int64   `gorm:"column:start_time;not null;comment:拼团开始时间" json:"start_time"`                      // 拼团开始时间
	StopTime      int64   `gorm:"column:stop_time;not null;comment:拼团结束时间" json:"stop_time"`                        // 拼团结束时间
	EffectiveTime int32   `gorm:"column:effective_time;not null;comment:拼团订单有效时间(小时)" json:"effective_time"`        // 拼团订单有效时间(小时)
	Cost          float64 `gorm:"column:cost;not null;default:0.00;comment:拼图商品成本" json:"cost"`                     // 拼图商品成本
	Browse        int32   `gorm:"column:browse;comment:浏览量" json:"browse"`                                          // 浏览量
	UnitName      string  `gorm:"column:unit_name;not null;comment:单位名" json:"unit_name"`                           // 单位名
	TempID        int32   `gorm:"column:temp_id;not null;comment:运费模板ID" json:"temp_id"`                            // 运费模板ID
	Weight        float64 `gorm:"column:weight;default:0.00;comment:重量" json:"weight"`                              // 重量
	Volume        float64 `gorm:"column:volume;default:0.00;comment:体积" json:"volume"`                              // 体积
	Num           int32   `gorm:"column:num;comment:单次购买数量" json:"num"`                                             // 单次购买数量
	Quota         int32   `gorm:"column:quota;not null;comment:限购总数" json:"quota"`                                  // 限购总数
	QuotaShow     int32   `gorm:"column:quota_show;not null;comment:限量总数显示" json:"quota_show"`                      // 限量总数显示
	OtPrice       float64 `gorm:"column:ot_price;not null;comment:原价" json:"ot_price"`                              // 原价
	OnceNum       int32   `gorm:"column:once_num;not null;comment:每个订单可购买数量" json:"once_num"`                       // 每个订单可购买数量
	VirtualRation int32   `gorm:"column:virtual_ration;not null;default:100;comment:虚拟成团百分比" json:"virtual_ration"` // 虚拟成团百分比
}

// TableName EbStoreCombination's table name
func (*EbStoreCombination) TableName() string {
	return TableNameEbStoreCombination
}
