// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemAttachment = "eb_system_attachment"

// EbSystemAttachment 附件管理表
type EbSystemAttachment struct {
	AttID      int32     `gorm:"column:att_id;primaryKey;autoIncrement:true" json:"att_id"`
	Name       string    `gorm:"column:name;not null;comment:附件名称" json:"name"`                                               // 附件名称
	AttDir     string    `gorm:"column:att_dir;not null;comment:附件路径" json:"att_dir"`                                         // 附件路径
	SattDir    string    `gorm:"column:satt_dir;comment:压缩图片路径" json:"satt_dir"`                                              // 压缩图片路径
	AttSize    string    `gorm:"column:att_size;not null;comment:附件大小" json:"att_size"`                                       // 附件大小
	AttType    string    `gorm:"column:att_type;not null;comment:附件类型" json:"att_type"`                                       // 附件类型
	Pid        int32     `gorm:"column:pid;not null;comment:分类ID0编辑器,1商品图片,2拼团图片,3砍价图片,4秒杀图片,5文章图片,6组合数据图， 7前台用户" json:"pid"` // 分类ID0编辑器,1商品图片,2拼团图片,3砍价图片,4秒杀图片,5文章图片,6组合数据图， 7前台用户
	ImageType  int32     `gorm:"column:image_type;not null;default:1;comment:图片上传类型 1本地 2七牛云 3OSS 4COS" json:"image_type"`    // 图片上传类型 1本地 2七牛云 3OSS 4COS
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                // 更新时间
}

// TableName EbSystemAttachment's table name
func (*EbSystemAttachment) TableName() string {
	return TableNameEbSystemAttachment
}
