// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbStoreCoupon = "eb_store_coupon"

// EbStoreCoupon 优惠券表
type EbStoreCoupon struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:优惠券表ID" json:"id"`                     // 优惠券表ID
	Name             string    `gorm:"column:name;not null;comment:优惠券名称" json:"name"`                                       // 优惠券名称
	Money            float64   `gorm:"column:money;not null;default:0.00;comment:兑换的优惠券面值" json:"money"`                     // 兑换的优惠券面值
	IsLimited        bool      `gorm:"column:is_limited;comment:是否限量, 默认0 不限量， 1限量" json:"is_limited"`                       // 是否限量, 默认0 不限量， 1限量
	Total            int32     `gorm:"column:total;not null;comment:发放总数" json:"total"`                                      // 发放总数
	LastTotal        int32     `gorm:"column:last_total;comment:剩余数量" json:"last_total"`                                     // 剩余数量
	UseType          int32     `gorm:"column:use_type;not null;default:1;comment:使用类型 1 全场通用, 2 商品券, 3 品类券" json:"use_type"` // 使用类型 1 全场通用, 2 商品券, 3 品类券
	PrimaryKey       string    `gorm:"column:primary_key;not null;comment:所属商品id / 分类id" json:"primary_key"`                 // 所属商品id / 分类id
	MinPrice         float64   `gorm:"column:min_price;not null;default:0.00;comment:最低消费，0代表不限制" json:"min_price"`          // 最低消费，0代表不限制
	ReceiveStartTime time.Time `gorm:"column:receive_start_time;not null;comment:可领取开始时间" json:"receive_start_time"`         // 可领取开始时间
	ReceiveEndTime   time.Time `gorm:"column:receive_end_time;comment:可领取结束时间" json:"receive_end_time"`                      // 可领取结束时间
	IsFixedTime      bool      `gorm:"column:is_fixed_time;comment:是否固定使用时间, 默认0 否， 1是" json:"is_fixed_time"`                // 是否固定使用时间, 默认0 否， 1是
	UseStartTime     time.Time `gorm:"column:use_start_time;comment:可使用时间范围 开始时间" json:"use_start_time"`                     // 可使用时间范围 开始时间
	UseEndTime       time.Time `gorm:"column:use_end_time;comment:可使用时间范围 结束时间" json:"use_end_time"`                         // 可使用时间范围 结束时间
	Day              int32     `gorm:"column:day;comment:天数" json:"day"`                                                     // 天数
	Type             int32     `gorm:"column:type;not null;default:1;comment:优惠券类型 1 手动领取, 2 新人券, 3 赠送券" json:"type"`        // 优惠券类型 1 手动领取, 2 新人券, 3 赠送券
	Sort             int32     `gorm:"column:sort;not null;default:1;comment:排序" json:"sort"`                                // 排序
	Status           int32     `gorm:"column:status;not null;default:1;comment:状态（0：关闭，1：开启）" json:"status"`                 // 状态（0：关闭，1：开启）
	IsDel            int32     `gorm:"column:is_del;not null;comment:是否删除 状态（0：否，1：是）" json:"is_del"`                        // 是否删除 状态（0：否，1：是）
	CreateTime       time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`         // 创建时间
	UpdateTime       time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`         // 更新时间
}

// TableName EbStoreCoupon's table name
func (*EbStoreCoupon) TableName() string {
	return TableNameEbStoreCoupon
}
