// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemStoreStaff = "eb_system_store_staff"

// EbSystemStoreStaff 门店店员表
type EbSystemStoreStaff struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int32     `gorm:"column:uid;not null;comment:管理员id" json:"uid"`                                          // 管理员id
	Avatar       string    `gorm:"column:avatar;not null;comment:店员头像" json:"avatar"`                                     // 店员头像
	StoreID      int32     `gorm:"column:store_id;not null;comment:门店id" json:"store_id"`                                 // 门店id
	StaffName    string    `gorm:"column:staff_name;comment:店员名称" json:"staff_name"`                                      // 店员名称
	Phone        string    `gorm:"column:phone;comment:手机号码" json:"phone"`                                                // 手机号码
	VerifyStatus int32     `gorm:"column:verify_status;not null;comment:核销开关" json:"verify_status"`                       // 核销开关
	Status       int32     `gorm:"column:status;default:1;comment:状态" json:"status"`                                      // 状态
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"` // 添加时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemStoreStaff's table name
func (*EbSystemStoreStaff) TableName() string {
	return TableNameEbSystemStoreStaff
}
