// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProductAttr = "eb_store_product_attr"

// EbStoreProductAttr 商品属性表
type EbStoreProductAttr struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ProductID  int32  `gorm:"column:product_id;not null;comment:商品ID" json:"product_id"`    // 商品ID
	AttrName   string `gorm:"column:attr_name;not null;comment:属性名" json:"attr_name"`       // 属性名
	AttrValues string `gorm:"column:attr_values;not null;comment:属性值" json:"attr_values"`   // 属性值
	Type       bool   `gorm:"column:type;comment:活动类型 0=商品，1=秒杀，2=砍价，3=拼团" json:"type"`     // 活动类型 0=商品，1=秒杀，2=砍价，3=拼团
	IsDel      bool   `gorm:"column:is_del;not null;comment:是否删除,0-否，1-是" json:"is_del"`    // 是否删除,0-否，1-是
}

// TableName EbStoreProductAttr's table name
func (*EbStoreProductAttr) TableName() string {
	return TableNameEbStoreProductAttr
}
