// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemFormTemp = "eb_system_form_temp"

// EbSystemFormTemp 表单模板
type EbSystemFormTemp struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:表单模板id" json:"id"`             // 表单模板id
	Name       string    `gorm:"column:name;not null;comment:表单名称" json:"name"`                                // 表单名称
	Info       string    `gorm:"column:info;not null;comment:表单简介" json:"info"`                                // 表单简介
	Content    string    `gorm:"column:content;not null;comment:表单内容" json:"content"`                          // 表单内容
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemFormTemp's table name
func (*EbSystemFormTemp) TableName() string {
	return TableNameEbSystemFormTemp
}
