// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProductDescription = "eb_store_product_description"

// EbStoreProductDescription 商品描述表
type EbStoreProductDescription struct {
	ProductID   int32  `gorm:"column:product_id;not null;comment:商品ID" json:"product_id"`   // 商品ID
	Description string `gorm:"column:description;not null;comment:商品详情" json:"description"` // 商品详情
	Type        bool   `gorm:"column:type;not null;comment:商品类型" json:"type"`               // 商品类型
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName EbStoreProductDescription's table name
func (*EbStoreProductDescription) TableName() string {
	return TableNameEbStoreProductDescription
}
