// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProductCoupon = "eb_store_product_coupon"

// EbStoreProductCoupon 商品优惠券表
type EbStoreProductCoupon struct {
	ID            int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID     int32 `gorm:"column:product_id;not null;comment:商品id" json:"product_id"`            // 商品id
	IssueCouponID int32 `gorm:"column:issue_coupon_id;not null;comment:优惠劵id" json:"issue_coupon_id"` // 优惠劵id
	AddTime       int32 `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`                // 添加时间
}

// TableName EbStoreProductCoupon's table name
func (*EbStoreProductCoupon) TableName() string {
	return TableNameEbStoreProductCoupon
}
