// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProductCate = "eb_store_product_cate"

// EbStoreProductCate 商品分类辅助表
type EbStoreProductCate struct {
	ID        int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID int32 `gorm:"column:product_id;not null;comment:商品id" json:"product_id"` // 商品id
	CateID    int32 `gorm:"column:cate_id;not null;comment:分类id" json:"cate_id"`       // 分类id
	AddTime   int32 `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`     // 添加时间
}

// TableName EbStoreProductCate's table name
func (*EbStoreProductCate) TableName() string {
	return TableNameEbStoreProductCate
}
