// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemNotification = "eb_system_notification"

// EbSystemNotification 通知设置表
type EbSystemNotification struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                          // id
	Mark        string    `gorm:"column:mark;not null;comment:标识" json:"mark"`                                           // 标识
	Type        string    `gorm:"column:type;not null;comment:通知类型" json:"type"`                                         // 通知类型
	Description string    `gorm:"column:description;not null;comment:通知场景说明" json:"description"`                         // 通知场景说明
	IsWechat    int32     `gorm:"column:is_wechat;not null;comment:公众号模板消息（0：不存在，1：开启，2：关闭）" json:"is_wechat"`           // 公众号模板消息（0：不存在，1：开启，2：关闭）
	WechatID    int32     `gorm:"column:wechat_id;not null;comment:模板消息id" json:"wechat_id"`                             // 模板消息id
	IsRoutine   int32     `gorm:"column:is_routine;not null;comment:小程序订阅消息（0：不存在，1：开启，2：关闭）" json:"is_routine"`         // 小程序订阅消息（0：不存在，1：开启，2：关闭）
	RoutineID   int32     `gorm:"column:routine_id;not null;comment:订阅消息id" json:"routine_id"`                           // 订阅消息id
	IsSms       int32     `gorm:"column:is_sms;not null;comment:发送短信（0：不存在，1：开启，2：关闭）" json:"is_sms"`                    // 发送短信（0：不存在，1：开启，2：关闭）
	SmsID       int32     `gorm:"column:sms_id;not null;comment:短信id" json:"sms_id"`                                     // 短信id
	SendType    int32     `gorm:"column:send_type;not null;default:1;comment:发送类型（1：用户，2：管理员）" json:"send_type"`         // 发送类型（1：用户，2：管理员）
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName EbSystemNotification's table name
func (*EbSystemNotification) TableName() string {
	return TableNameEbSystemNotification
}
