// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbStoreProductAttrValue = "eb_store_product_attr_value"

// EbStoreProductAttrValue 商品属性值表
type EbStoreProductAttrValue struct {
	ID           int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                  // 主键
	ProductID    int32   `gorm:"column:product_id;not null;comment:商品ID" json:"product_id"`                     // 商品ID
	Suk          string  `gorm:"column:suk;not null;comment:商品属性索引值 (attr_value|attr_value[|....])" json:"suk"` // 商品属性索引值 (attr_value|attr_value[|....])
	Stock        int32   `gorm:"column:stock;not null;comment:属性对应的库存" json:"stock"`                            // 属性对应的库存
	Sales        int32   `gorm:"column:sales;not null;comment:销量" json:"sales"`                                 // 销量
	Price        float64 `gorm:"column:price;not null;comment:属性金额" json:"price"`                               // 属性金额
	Image        string  `gorm:"column:image;comment:图片" json:"image"`                                          // 图片
	Unique       string  `gorm:"column:unique;not null;comment:唯一值" json:"unique"`                              // 唯一值
	Cost         float64 `gorm:"column:cost;not null;default:0.00;comment:成本价" json:"cost"`                     // 成本价
	BarCode      string  `gorm:"column:bar_code;not null;comment:商品条码" json:"bar_code"`                         // 商品条码
	OtPrice      float64 `gorm:"column:ot_price;not null;default:0.00;comment:原价" json:"ot_price"`              // 原价
	Weight       float64 `gorm:"column:weight;not null;default:0.00;comment:重量" json:"weight"`                  // 重量
	Volume       float64 `gorm:"column:volume;not null;default:0.00;comment:体积" json:"volume"`                  // 体积
	Brokerage    float64 `gorm:"column:brokerage;not null;default:0.00;comment:一级返佣" json:"brokerage"`          // 一级返佣
	BrokerageTwo float64 `gorm:"column:brokerage_two;not null;default:0.00;comment:二级返佣" json:"brokerage_two"`  // 二级返佣
	Type         bool    `gorm:"column:type;comment:活动类型 0=商品，1=秒杀，2=砍价，3=拼团" json:"type"`                      // 活动类型 0=商品，1=秒杀，2=砍价，3=拼团
	Quota        int32   `gorm:"column:quota;comment:活动限购数量" json:"quota"`                                      // 活动限购数量
	QuotaShow    int32   `gorm:"column:quota_show;comment:活动限购数量显示" json:"quota_show"`                          // 活动限购数量显示
	AttrValue    string  `gorm:"column:attr_value;comment:attr_values 创建更新时的属性对应" json:"attr_value"`            // attr_values 创建更新时的属性对应
	IsDel        bool    `gorm:"column:is_del;not null;comment:是否删除,0-否，1-是" json:"is_del"`                     // 是否删除,0-否，1-是
}

// TableName EbStoreProductAttrValue's table name
func (*EbStoreProductAttrValue) TableName() string {
	return TableNameEbStoreProductAttrValue
}
