// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemUserLevel = "eb_system_user_level"

// EbSystemUserLevel 普通会员等级
type EbSystemUserLevel struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:会员名称" json:"name"`                                // 会员名称
	Experience int32     `gorm:"column:experience;not null;comment:达到多少升级经验" json:"experience"`                // 达到多少升级经验
	IsShow     bool      `gorm:"column:is_show;not null;comment:是否显示 1=显示,0=隐藏" json:"is_show"`                // 是否显示 1=显示,0=隐藏
	Grade      int32     `gorm:"column:grade;not null;comment:会员等级" json:"grade"`                              // 会员等级
	Discount   int32     `gorm:"column:discount;not null;default:100;comment:享受折扣" json:"discount"`            // 享受折扣
	Icon       string    `gorm:"column:icon;not null;comment:会员图标" json:"icon"`                                // 会员图标
	IsDel      bool      `gorm:"column:is_del;not null;comment:是否删除.1=删除,0=未删除" json:"is_del"`                 // 是否删除.1=删除,0=未删除
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbSystemUserLevel's table name
func (*EbSystemUserLevel) TableName() string {
	return TableNameEbSystemUserLevel
}
