// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbSystemAdmin = "eb_system_admin"

// EbSystemAdmin 后台管理员表
type EbSystemAdmin struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:后台管理员表ID" json:"id"`                             // 后台管理员表ID
	Account    string    `gorm:"column:account;not null;comment:后台管理员账号" json:"account"`                                         // 后台管理员账号
	Pwd        string    `gorm:"column:pwd;not null;comment:后台管理员密码" json:"pwd"`                                                 // 后台管理员密码
	RealName   string    `gorm:"column:real_name;not null;comment:后台管理员姓名" json:"real_name"`                                     // 后台管理员姓名
	Roles      string    `gorm:"column:roles;not null;comment:后台管理员权限(menus_id)" json:"roles"`                                   // 后台管理员权限(menus_id)
	LastIP     string    `gorm:"column:last_ip;comment:后台管理员最后一次登录ip" json:"last_ip"`                                            // 后台管理员最后一次登录ip
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:后台管理员最后一次登录时间" json:"update_time"` // 后台管理员最后一次登录时间
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:后台管理员添加时间" json:"create_time"`     // 后台管理员添加时间
	LoginCount int32     `gorm:"column:login_count;not null;comment:登录次数" json:"login_count"`                                    // 登录次数
	Level      int32     `gorm:"column:level;not null;default:1;comment:后台管理员级别" json:"level"`                                   // 后台管理员级别
	Status     int32     `gorm:"column:status;not null;default:1;comment:后台管理员状态 1有效0无效" json:"status"`                          // 后台管理员状态 1有效0无效
	IsDel      int32     `gorm:"column:is_del;not null" json:"is_del"`
	Phone      string    `gorm:"column:phone;comment:手机号码" json:"phone"`     // 手机号码
	IsSms      int32     `gorm:"column:is_sms;comment:是否接收短信" json:"is_sms"` // 是否接收短信
}

// TableName EbSystemAdmin's table name
func (*EbSystemAdmin) TableName() string {
	return TableNameEbSystemAdmin
}
