// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbTemplateMessage = "eb_template_message"

// EbTemplateMessage 微信模板
type EbTemplateMessage struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:模板id" json:"id"`                        // 模板id
	Type       bool      `gorm:"column:type;not null;comment:0=订阅消息,1=微信模板消息" json:"type"`                              // 0=订阅消息,1=微信模板消息
	TempKey    string    `gorm:"column:temp_key;not null;comment:模板编号" json:"temp_key"`                                 // 模板编号
	Name       string    `gorm:"column:name;not null;comment:模板名" json:"name"`                                          // 模板名
	Content    string    `gorm:"column:content;not null;comment:回复内容" json:"content"`                                   // 回复内容
	TempID     string    `gorm:"column:temp_id;comment:模板ID" json:"temp_id"`                                            // 模板ID
	Status     int32     `gorm:"column:status;not null;default:1;comment:状态" json:"status"`                             // 状态
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"` // 添加时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbTemplateMessage's table name
func (*EbTemplateMessage) TableName() string {
	return TableNameEbTemplateMessage
}
