// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserIntegralRecord = "eb_user_integral_record"

// EbUserIntegralRecord 用户积分记录表
type EbUserIntegralRecord struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录id" json:"id"`                           // 记录id
	UID        int32     `gorm:"column:uid;not null;comment:用户uid" json:"uid"`                                             // 用户uid
	LinkID     string    `gorm:"column:link_id;not null;default:0;comment:关联id-orderNo,(sign,system默认为0）" json:"link_id"`  // 关联id-orderNo,(sign,system默认为0）
	LinkType   string    `gorm:"column:link_type;not null;default:order;comment:关联类型（order,sign,system）" json:"link_type"` // 关联类型（order,sign,system）
	Type       int32     `gorm:"column:type;not null;default:1;comment:类型：1-增加，2-扣减" json:"type"`                          // 类型：1-增加，2-扣减
	Title      string    `gorm:"column:title;not null;comment:标题" json:"title"`                                            // 标题
	Integral   int32     `gorm:"column:integral;not null;comment:积分" json:"integral"`                                      // 积分
	Balance    int32     `gorm:"column:balance;not null;comment:剩余" json:"balance"`                                        // 剩余
	Mark       string    `gorm:"column:mark;not null;comment:备注" json:"mark"`                                              // 备注
	Status     bool      `gorm:"column:status;not null;default:1;comment:状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款）" json:"status"`   // 状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款）
	FrozenTime int32     `gorm:"column:frozen_time;not null;comment:冻结期时间（天）" json:"frozen_time"`                          // 冻结期时间（天）
	ThawTime   int64     `gorm:"column:thaw_time;not null;comment:解冻时间" json:"thaw_time"`                                  // 解冻时间
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"`             // 添加时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`             // 更新时间
}

// TableName EbUserIntegralRecord's table name
func (*EbUserIntegralRecord) TableName() string {
	return TableNameEbUserIntegralRecord
}
