// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserBill = "eb_user_bill"

// EbUserBill 用户账单表
type EbUserBill struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户账单id" json:"id"`              // 用户账单id
	UID        int32     `gorm:"column:uid;not null;comment:用户uid" json:"uid"`                                  // 用户uid
	LinkID     string    `gorm:"column:link_id;not null;default:0;comment:关联id" json:"link_id"`                 // 关联id
	Pm         int32     `gorm:"column:pm;not null;comment:0 = 支出 1 = 获得" json:"pm"`                            // 0 = 支出 1 = 获得
	Title      string    `gorm:"column:title;not null;comment:账单标题" json:"title"`                               // 账单标题
	Category   string    `gorm:"column:category;not null;comment:明细种类" json:"category"`                         // 明细种类
	Type       string    `gorm:"column:type;not null;comment:明细类型" json:"type"`                                 // 明细类型
	Number     float64   `gorm:"column:number;not null;default:0.00;comment:明细数字" json:"number"`                // 明细数字
	Balance    float64   `gorm:"column:balance;not null;default:0.00;comment:剩余" json:"balance"`                // 剩余
	Mark       string    `gorm:"column:mark;not null;comment:备注" json:"mark"`                                   // 备注
	Status     bool      `gorm:"column:status;not null;default:1;comment:0 = 带确定 1 = 有效 -1 = 无效" json:"status"` // 0 = 带确定 1 = 有效 -1 = 无效
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"`  // 添加时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`  // 更新时间
}

// TableName EbUserBill's table name
func (*EbUserBill) TableName() string {
	return TableNameEbUserBill
}
