// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserRecharge = "eb_user_recharge"

// EbUserRecharge 用户充值表
type EbUserRecharge struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int32     `gorm:"column:uid;comment:充值用户UID" json:"uid"`                                        // 充值用户UID
	OrderID      string    `gorm:"column:order_id;comment:订单号" json:"order_id"`                                  // 订单号
	Price        float64   `gorm:"column:price;comment:充值金额" json:"price"`                                       // 充值金额
	GivePrice    float64   `gorm:"column:give_price;not null;default:0.00;comment:购买赠送金额" json:"give_price"`     // 购买赠送金额
	RechargeType string    `gorm:"column:recharge_type;comment:充值类型" json:"recharge_type"`                       // 充值类型
	Paid         bool      `gorm:"column:paid;comment:是否充值" json:"paid"`                                         // 是否充值
	PayTime      time.Time `gorm:"column:pay_time;comment:充值支付时间" json:"pay_time"`                               // 充值支付时间
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:充值时间" json:"create_time"` // 充值时间
	RefundPrice  float64   `gorm:"column:refund_price;default:0.00;comment:退款金额" json:"refund_price"`            // 退款金额
}

// TableName EbUserRecharge's table name
func (*EbUserRecharge) TableName() string {
	return TableNameEbUserRecharge
}
