// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserLevel = "eb_user_level"

// EbUserLevel 用户等级记录表
type EbUserLevel struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID         int32     `gorm:"column:uid;not null;comment:用户uid" json:"uid"`                                 // 用户uid
	LevelID     int32     `gorm:"column:level_id;not null;comment:等级vip" json:"level_id"`                       // 等级vip
	Grade       int32     `gorm:"column:grade;not null;comment:会员等级" json:"grade"`                              // 会员等级
	Status      bool      `gorm:"column:status;not null;comment:0:禁止,1:正常" json:"status"`                       // 0:禁止,1:正常
	Mark        string    `gorm:"column:mark;not null;comment:备注" json:"mark"`                                  // 备注
	Remind      bool      `gorm:"column:remind;not null;comment:是否已通知" json:"remind"`                           // 是否已通知
	IsDel       bool      `gorm:"column:is_del;not null;comment:是否删除,0=未删除,1=删除" json:"is_del"`                 // 是否删除,0=未删除,1=删除
	Discount    int32     `gorm:"column:discount;not null;default:100;comment:享受折扣" json:"discount"`            // 享受折扣
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	ExpiredTime time.Time `gorm:"column:expired_time;comment:过期时间" json:"expired_time"`                         // 过期时间
}

// TableName EbUserLevel's table name
func (*EbUserLevel) TableName() string {
	return TableNameEbUserLevel
}
