// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUser = "eb_user"

// EbUser 用户表
type EbUser struct {
	UID            int32     `gorm:"column:uid;primaryKey;autoIncrement:true;comment:用户id" json:"uid"`                      // 用户id
	Account        string    `gorm:"column:account;not null;comment:用户账号" json:"account"`                                   // 用户账号
	Pwd            string    `gorm:"column:pwd;comment:用户密码" json:"pwd"`                                                    // 用户密码
	RealName       string    `gorm:"column:real_name;comment:真实姓名" json:"real_name"`                                        // 真实姓名
	Birthday       string    `gorm:"column:birthday;comment:生日" json:"birthday"`                                            // 生日
	CardID         string    `gorm:"column:card_id;comment:身份证号码" json:"card_id"`                                           // 身份证号码
	Mark           string    `gorm:"column:mark;comment:用户备注" json:"mark"`                                                  // 用户备注
	PartnerID      int32     `gorm:"column:partner_id;comment:合伙人id" json:"partner_id"`                                     // 合伙人id
	GroupID        string    `gorm:"column:group_id;comment:用户分组id" json:"group_id"`                                        // 用户分组id
	TagID          string    `gorm:"column:tag_id;comment:标签id" json:"tag_id"`                                              // 标签id
	Nickname       string    `gorm:"column:nickname;comment:用户昵称" json:"nickname"`                                          // 用户昵称
	Avatar         string    `gorm:"column:avatar;comment:用户头像" json:"avatar"`                                              // 用户头像
	Phone          string    `gorm:"column:phone;comment:手机号码" json:"phone"`                                                // 手机号码
	AddIP          string    `gorm:"column:add_ip;comment:添加ip" json:"add_ip"`                                              // 添加ip
	LastIP         string    `gorm:"column:last_ip;comment:最后一次登录ip" json:"last_ip"`                                        // 最后一次登录ip
	NowMoney       float64   `gorm:"column:now_money;default:0.00;comment:用户余额" json:"now_money"`                           // 用户余额
	BrokeragePrice float64   `gorm:"column:brokerage_price;default:0.00;comment:佣金金额" json:"brokerage_price"`               // 佣金金额
	Integral       int32     `gorm:"column:integral;comment:用户剩余积分" json:"integral"`                                        // 用户剩余积分
	Experience     int32     `gorm:"column:experience;comment:用户剩余经验" json:"experience"`                                    // 用户剩余经验
	SignNum        int32     `gorm:"column:sign_num;comment:连续签到天数" json:"sign_num"`                                        // 连续签到天数
	Status         bool      `gorm:"column:status;default:1;comment:1为正常，0为禁止" json:"status"`                               // 1为正常，0为禁止
	Level          int32     `gorm:"column:level;comment:等级" json:"level"`                                                  // 等级
	SpreadUID      int32     `gorm:"column:spread_uid;comment:推广员id" json:"spread_uid"`                                     // 推广员id
	SpreadTime     time.Time `gorm:"column:spread_time;comment:推广员关联时间" json:"spread_time"`                                 // 推广员关联时间
	UserType       string    `gorm:"column:user_type;not null;comment:用户类型" json:"user_type"`                               // 用户类型
	IsPromoter     int32     `gorm:"column:is_promoter;comment:是否为推广员" json:"is_promoter"`                                  // 是否为推广员
	PayCount       int32     `gorm:"column:pay_count;comment:用户购买次数" json:"pay_count"`                                      // 用户购买次数
	SpreadCount    int32     `gorm:"column:spread_count;comment:下级人数" json:"spread_count"`                                  // 下级人数
	Addres         string    `gorm:"column:addres;comment:详细地址" json:"addres"`                                              // 详细地址
	Adminid        int32     `gorm:"column:adminid;comment:管理员编号" json:"adminid"`                                           // 管理员编号
	LoginType      string    `gorm:"column:login_type;not null;comment:用户登陆类型，h5,wechat,routine" json:"login_type"`         // 用户登陆类型，h5,wechat,routine
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	LastLoginTime  time.Time `gorm:"column:last_login_time;comment:最后一次登录时间" json:"last_login_time"`                        // 最后一次登录时间
	CleanTime      time.Time `gorm:"column:clean_time;comment:清除时间" json:"clean_time"`                                      // 清除时间
	Path           string    `gorm:"column:path;not null;default:/0/;comment:推广等级记录" json:"path"`                           // 推广等级记录
	Subscribe      int32     `gorm:"column:subscribe;comment:是否关注公众号" json:"subscribe"`                                     // 是否关注公众号
	SubscribeTime  time.Time `gorm:"column:subscribe_time;comment:关注公众号时间" json:"subscribe_time"`                           // 关注公众号时间
	Sex            bool      `gorm:"column:sex;default:1;comment:性别，0未知，1男，2女，3保密" json:"sex"`                              // 性别，0未知，1男，2女，3保密
	Country        string    `gorm:"column:country;default:CN;comment:国家，中国CN，其他OTHER" json:"country"`                      // 国家，中国CN，其他OTHER
	PromoterTime   time.Time `gorm:"column:promoter_time;comment:成为分销员时间" json:"promoter_time"`                             // 成为分销员时间
}

// TableName EbUser's table name
func (*EbUser) TableName() string {
	return TableNameEbUser
}
