// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserAddress = "eb_user_address"

// EbUserAddress 用户地址表
type EbUserAddress struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户地址id" json:"id"`             // 用户地址id
	UID        int32     `gorm:"column:uid;not null;comment:用户id" json:"uid"`                                  // 用户id
	RealName   string    `gorm:"column:real_name;not null;comment:收货人姓名" json:"real_name"`                     // 收货人姓名
	Phone      string    `gorm:"column:phone;not null;comment:收货人电话" json:"phone"`                             // 收货人电话
	Province   string    `gorm:"column:province;not null;comment:收货人所在省" json:"province"`                      // 收货人所在省
	City       string    `gorm:"column:city;not null;comment:收货人所在市" json:"city"`                              // 收货人所在市
	CityID     int32     `gorm:"column:city_id;not null;comment:城市id" json:"city_id"`                          // 城市id
	District   string    `gorm:"column:district;not null;comment:收货人所在区" json:"district"`                      // 收货人所在区
	Detail     string    `gorm:"column:detail;not null;comment:收货人详细地址" json:"detail"`                         // 收货人详细地址
	PostCode   int32     `gorm:"column:post_code;not null;comment:邮编" json:"post_code"`                        // 邮编
	Longitude  string    `gorm:"column:longitude;not null;default:0;comment:经度" json:"longitude"`              // 经度
	Latitude   string    `gorm:"column:latitude;not null;default:0;comment:纬度" json:"latitude"`                // 纬度
	IsDefault  int32     `gorm:"column:is_default;not null;comment:是否默认" json:"is_default"`                    // 是否默认
	IsDel      int32     `gorm:"column:is_del;not null;comment:是否删除" json:"is_del"`                            // 是否删除
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbUserAddress's table name
func (*EbUserAddress) TableName() string {
	return TableNameEbUserAddress
}
