// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserToken = "eb_user_token"

// EbUserToken mapped from table <eb_user_token>
type EbUserToken struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID         int32     `gorm:"column:uid;not null;comment:用户 id" json:"uid"`                                                   // 用户 id
	Token       string    `gorm:"column:token;not null;comment:token" json:"token"`                                               // token
	Type        bool      `gorm:"column:type;default:1;comment:类型，1 公众号， 2 小程序, 3 unionid, 5AppIos,6AppAndroid,7ios" json:"type"` // 类型，1 公众号， 2 小程序, 3 unionid, 5AppIos,6AppAndroid,7ios
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`          // 创建时间
	ExpiresTime time.Time `gorm:"column:expires_time;comment:到期时间" json:"expires_time"`                                           // 到期时间
	LoginIP     string    `gorm:"column:login_ip;comment:登录ip" json:"login_ip"`                                                   // 登录ip
}

// TableName EbUserToken's table name
func (*EbUserToken) TableName() string {
	return TableNameEbUserToken
}
