// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserBrokerageRecord = "eb_user_brokerage_record"

// EbUserBrokerageRecord 用户佣金记录表
type EbUserBrokerageRecord struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录id" json:"id"`                                // 记录id
	UID            int32     `gorm:"column:uid;not null;comment:用户uid" json:"uid"`                                                  // 用户uid
	LinkID         string    `gorm:"column:link_id;not null;default:0;comment:关联id（orderNo,提现id）" json:"link_id"`                   // 关联id（orderNo,提现id）
	LinkType       string    `gorm:"column:link_type;not null;default:0;comment:关联类型（order,extract，yue）" json:"link_type"`          // 关联类型（order,extract，yue）
	Type           int32     `gorm:"column:type;not null;default:1;comment:类型：1-增加，2-扣减（提现）" json:"type"`                           // 类型：1-增加，2-扣减（提现）
	Title          string    `gorm:"column:title;not null;comment:标题" json:"title"`                                                 // 标题
	Price          float64   `gorm:"column:price;not null;default:0.00;comment:金额" json:"price"`                                    // 金额
	Balance        float64   `gorm:"column:balance;not null;default:0.00;comment:剩余" json:"balance"`                                // 剩余
	Mark           string    `gorm:"column:mark;not null;comment:备注" json:"mark"`                                                   // 备注
	Status         bool      `gorm:"column:status;not null;default:1;comment:状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款），5-提现申请" json:"status"` // 状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款），5-提现申请
	FrozenTime     int32     `gorm:"column:frozen_time;not null;comment:冻结期时间（天）" json:"frozen_time"`                               // 冻结期时间（天）
	ThawTime       int64     `gorm:"column:thaw_time;not null;comment:解冻时间" json:"thaw_time"`                                       // 解冻时间
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_time"`                  // 添加时间
	UpdateTime     time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`                  // 更新时间
	BrokerageLevel int32     `gorm:"column:brokerage_level;comment:分销等级" json:"brokerage_level"`                                    // 分销等级
}

// TableName EbUserBrokerageRecord's table name
func (*EbUserBrokerageRecord) TableName() string {
	return TableNameEbUserBrokerageRecord
}
