// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbUserExtract = "eb_user_extract"

// EbUserExtract 用户提现表
type EbUserExtract struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int32     `gorm:"column:uid" json:"uid"`
	RealName     string    `gorm:"column:real_name;comment:名称" json:"real_name"`                                                   // 名称
	ExtractType  string    `gorm:"column:extract_type;default:bank;comment:bank = 银行卡 alipay = 支付宝 weixin=微信" json:"extract_type"` // bank = 银行卡 alipay = 支付宝 weixin=微信
	BankCode     string    `gorm:"column:bank_code;comment:银行卡" json:"bank_code"`                                                  // 银行卡
	BankAddress  string    `gorm:"column:bank_address;comment:开户地址" json:"bank_address"`                                           // 开户地址
	AlipayCode   string    `gorm:"column:alipay_code;comment:支付宝账号" json:"alipay_code"`                                            // 支付宝账号
	ExtractPrice float64   `gorm:"column:extract_price;default:0.00;comment:提现金额" json:"extract_price"`                            // 提现金额
	Mark         string    `gorm:"column:mark" json:"mark"`
	Balance      float64   `gorm:"column:balance;default:0.00" json:"balance"`
	FailMsg      string    `gorm:"column:fail_msg;comment:无效原因" json:"fail_msg"`                                 // 无效原因
	Status       int32     `gorm:"column:status;comment:-1 未通过 0 审核中 1 已提现" json:"status"`                       // -1 未通过 0 审核中 1 已提现
	Wechat       string    `gorm:"column:wechat;comment:微信号" json:"wechat"`                                      // 微信号
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	FailTime     time.Time `gorm:"column:fail_time;default:CURRENT_TIMESTAMP;comment:失败时间" json:"fail_time"`     // 失败时间
	BankName     string    `gorm:"column:bank_name;comment:银行名称" json:"bank_name"`                               // 银行名称
	QrcodeURL    string    `gorm:"column:qrcode_url;comment:微信收款二维码" json:"qrcode_url"`                          // 微信收款二维码
}

// TableName EbUserExtract's table name
func (*EbUserExtract) TableName() string {
	return TableNameEbUserExtract
}
