// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEbUserGroup = "eb_user_group"

// EbUserGroup 用户分组表
type EbUserGroup struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GroupName string `gorm:"column:group_name;comment:用户分组名称" json:"group_name"` // 用户分组名称
}

// TableName EbUserGroup's table name
func (*EbUserGroup) TableName() string {
	return TableNameEbUserGroup
}
