// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbWechatReply = "eb_wechat_reply"

// EbWechatReply 微信关键字回复表
type EbWechatReply struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:微信关键字回复id" json:"id"`          // 微信关键字回复id
	Keywords   string    `gorm:"column:keywords;not null;comment:关键字" json:"keywords"`                         // 关键字
	Type       string    `gorm:"column:type;not null;comment:回复类型" json:"type"`                                // 回复类型
	Data       string    `gorm:"column:data;not null;comment:回复数据" json:"data"`                                // 回复数据
	Status     int32     `gorm:"column:status;not null;default:1;comment:回复状态 0=不可用  1 =可用" json:"status"`     // 回复状态 0=不可用  1 =可用
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbWechatReply's table name
func (*EbWechatReply) TableName() string {
	return TableNameEbWechatReply
}
