// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbWechatException = "eb_wechat_exceptions"

// EbWechatException 微信异常表
type EbWechatException struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                 // id
	Errcode    string    `gorm:"column:errcode;comment:错误码" json:"errcode"`                                    // 错误码
	Errmsg     string    `gorm:"column:errmsg;comment:错误信息" json:"errmsg"`                                     // 错误信息
	Data       string    `gorm:"column:data;comment:回复数据" json:"data"`                                         // 回复数据
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`                                       // 备注
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName EbWechatException's table name
func (*EbWechatException) TableName() string {
	return TableNameEbWechatException
}
