// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameShippingTemplates = "shipping_templates"

// ShippingTemplates 运费模板
type ShippingTemplates struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:编号" json:"id"`          // 编号
	Name      string                `gorm:"column:name;type:varchar(255);not null;comment:模板名称" json:"name"`                    // 模板名称
	Type      int64                 `gorm:"column:type;type:tinyint(1);not null;default:1;comment:计费方式" json:"type"`            // 计费方式
	Appoint   int64                 `gorm:"column:appoint;type:tinyint(1);not null;comment:指定包邮" json:"appoint"`                // 指定包邮
	Sort      int64                 `gorm:"column:sort;type:int(11);not null;comment:排序" json:"sort"`                           // 排序
	CreatedAt int64                 `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(3) unsigned;not null;comment:是否删除" json:"-"`          // 是否删除
}

// TableName ShippingTemplates's table name
func (*ShippingTemplates) TableName() string {
	return TableNameShippingTemplates
}
