// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSpuLog = "spu_log"

// SpuLog 商品日志表
type SpuLog struct {
	ID          int64                 `gorm:"column:id;type:int(10) unsigned;primaryKey;comment:主键" json:"id"`                                       // 主键
	SpuID       int64                 `gorm:"column:spu_id;type:int(10) unsigned;not null;comment:商品id" json:"spu_id"`                               // 商品id
	Details     string                `gorm:"column:details;type:varchar(255);not null;comment:操作内容" json:"details"`                                 // 操作内容
	OperatePort int64                 `gorm:"column:operate_port;type:tinyint(3) unsigned;not null;comment:操作端口(1-运营后台,2-商家后台)" json:"operate_port"` // 操作端口(1-运营后台,2-商家后台)
	ServerID    int64                 `gorm:"column:server_id;type:int(10) unsigned;not null;comment:商家id" json:"server_id"`                         // 商家id
	Version     int64                 `gorm:"column:version;type:int(10) unsigned;not null;comment:版本号" json:"version"`                              // 版本号
	CreatedBy   int64                 `gorm:"column:created_by;type:int(10) unsigned;not null;comment:创建时间" json:"created_by"`                       // 创建时间
	UpdatedBy   int64                 `gorm:"column:updated_by;type:int(10) unsigned;not null;comment:修改时间" json:"updated_by"`                       // 修改时间
	CreatedAt   int64                 `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt   int64                 `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:修改时间" json:"updated_at"`                    // 修改时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(3) unsigned;not null;comment:是否删除" json:"-"`                             // 是否删除
}

// TableName SpuLog's table name
func (*SpuLog) TableName() string {
	return TableNameSpuLog
}
