// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSpuPicture = "spu_picture"

// SpuPicture 商品图片表
type SpuPicture struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;comment:主键" json:"id"`                             // 主键
	SpuID     int64                 `gorm:"column:spu_id;type:int(10) unsigned;not null;comment:商品id" json:"spu_id"`            // 商品id
	Type      int64                 `gorm:"column:type;type:tinyint(1);not null;comment:图片类型(1:封面,2:视频)" json:"type"`           // 图片类型(1:封面,2:视频)
	Picture   string                `gorm:"column:picture;type:varchar(255);not null;comment:图片/视频" json:"picture"`             // 图片/视频
	Sort      int64                 `gorm:"column:sort;type:int(10) unsigned;not null;comment:排序" json:"sort"`                  // 排序
	CreatedAt int64                 `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(3) unsigned;not null;comment:是否删除" json:"-"`          // 是否删除
	CreatedBy int64                 `gorm:"column:created_by;type:int(10) unsigned;not null;comment:创建时间" json:"created_by"`    // 创建时间
	UpdatedBy int64                 `gorm:"column:updated_by;type:int(10) unsigned;not null;comment:修改时间" json:"updated_by"`    // 修改时间
}

// TableName SpuPicture's table name
func (*SpuPicture) TableName() string {
	return TableNameSpuPicture
}
