// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSpuService = "spu_service"

// SpuService 商品服务表
type SpuService struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;comment:主键" json:"id"`                             // 主键
	SpuID     int64                 `gorm:"column:spu_id;type:int(10) unsigned;not null;comment:商品id" json:"spu_id"`            // 商品id
	ServiceID int64                 `gorm:"column:service_id;type:int(10) unsigned;not null;comment:服务id" json:"service_id"`    // 服务id
	Type      int64                 `gorm:"column:type;type:tinyint(3) unsigned;not null;comment:类型" json:"type"`               // 类型
	Name      string                `gorm:"column:name;type:varchar(64);not null;comment:服务名称" json:"name"`                     // 服务名称
	CreatedAt int64                 `gorm:"column:created_at;type:bigint(20) unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint(20) unsigned;not null;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(3) unsigned;not null;comment:是否删除" json:"-"`          // 是否删除
	CreatedBy int64                 `gorm:"column:created_by;type:int(10) unsigned;not null;comment:创建时间" json:"created_by"`    // 创建时间
	UpdatedBy int64                 `gorm:"column:updated_by;type:int(10) unsigned;not null;comment:修改时间" json:"updated_by"`    // 修改时间
}

// TableName SpuService's table name
func (*SpuService) TableName() string {
	return TableNameSpuService
}
