// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameStoreProductAttr = "store_product_attr"

// StoreProductAttr 商品属性表
type StoreProductAttr struct {
	ID         int64                 `gorm:"column:id;type:mediumint;primaryKey;autoIncrement:true;comment:主键" json:"id"`             // 主键
	ProductID  int64                 `gorm:"column:product_id;type:int unsigned;not null;comment:商品ID" json:"product_id"`             // 商品ID
	AttrName   string                `gorm:"column:attr_name;type:varchar(32);not null;comment:属性名" json:"attr_name"`                 // 属性名
	AttrValues string                `gorm:"column:attr_values;type:varchar(1000);not null;comment:属性值" json:"attr_values"`           // 属性值
	Type       int64                 `gorm:"column:type;type:tinyint unsigned;not null;comment:活动类型 0=商品，1=秒杀，2=砍价，3=拼团" json:"type"` // 活动类型 0=商品，1=秒杀，2=砍价，3=拼团
	CreatedAt  int64                 `gorm:"column:created_at;type:bigint unsigned;not null;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt  int64                 `gorm:"column:updated_at;type:bigint unsigned;not null;comment:修改时间" json:"updated_at"`          // 修改时间
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint unsigned;not null;comment:是否删除" json:"-"`                  // 是否删除
}

// TableName StoreProductAttr's table name
func (*StoreProductAttr) TableName() string {
	return TableNameStoreProductAttr
}
