// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUser = "user"

// User 用户表
type User struct {
	UID            int64                 `gorm:"column:uid;type:int unsigned;primaryKey;autoIncrement:true;comment:用户id" json:"uid"`                          // 用户id
	Account        string                `gorm:"column:account;type:varchar(32);not null;comment:用户账号" json:"account"`                                        // 用户账号
	Pwd            string                `gorm:"column:pwd;type:varchar(32);not null;comment:用户密码" json:"pwd"`                                                // 用户密码
	RealName       string                `gorm:"column:real_name;type:varchar(25);not null;comment:真实姓名" json:"real_name"`                                    // 真实姓名
	Birthday       string                `gorm:"column:birthday;type:varchar(32);not null;comment:生日" json:"birthday"`                                        // 生日
	CardID         string                `gorm:"column:card_id;type:varchar(20);not null;comment:身份证号码" json:"card_id"`                                       // 身份证号码
	Mark           string                `gorm:"column:mark;type:varchar(255);not null;comment:用户备注" json:"mark"`                                             // 用户备注
	PartnerID      int64                 `gorm:"column:partner_id;type:int unsigned;not null;comment:合伙人id" json:"partner_id"`                                // 合伙人id
	GroupID        string                `gorm:"column:group_id;type:varchar(255);not null;comment:用户分组id" json:"group_id"`                                   // 用户分组id
	TagID          string                `gorm:"column:tag_id;type:varchar(255);not null;comment:标签id" json:"tag_id"`                                         // 标签id
	Nickname       string                `gorm:"column:nickname;type:varchar(255);not null;comment:用户昵称" json:"nickname"`                                     // 用户昵称
	Avatar         string                `gorm:"column:avatar;type:varchar(256);not null;comment:用户头像" json:"avatar"`                                         // 用户头像
	Phone          string                `gorm:"column:phone;type:char(15);not null;comment:手机号码" json:"phone"`                                               // 手机号码
	AddIP          string                `gorm:"column:add_ip;type:varchar(16);not null;comment:添加ip" json:"add_ip"`                                          // 添加ip
	LastIP         string                `gorm:"column:last_ip;type:varchar(16);not null;comment:最后一次登录ip" json:"last_ip"`                                    // 最后一次登录ip
	NowMoney       string                `gorm:"column:now_money;type:decimal(16,2) unsigned;not null;default:0.00;comment:用户余额" json:"now_money"`            // 用户余额
	BrokeragePrice string                `gorm:"column:brokerage_price;type:decimal(8,2) unsigned;not null;default:0.00;comment:佣金金额" json:"brokerage_price"` // 佣金金额
	Integral       int64                 `gorm:"column:integral;type:int unsigned;not null;comment:用户剩余积分" json:"integral"`                                   // 用户剩余积分
	Experience     int64                 `gorm:"column:experience;type:int unsigned;not null;comment:用户剩余经验" json:"experience"`                               // 用户剩余经验
	SignNum        int64                 `gorm:"column:sign_num;type:int unsigned;not null;comment:连续签到天数" json:"sign_num"`                                   // 连续签到天数
	Status         int64                 `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:1为正常，0为禁止" json:"status"`                      // 1为正常，0为禁止
	Level          int64                 `gorm:"column:level;type:tinyint unsigned;not null;comment:等级" json:"level"`                                         // 等级
	SpreadUID      int64                 `gorm:"column:spread_uid;type:int unsigned;not null;comment:推广员id" json:"spread_uid"`                                // 推广员id
	SpreadTime     int64                 `gorm:"column:spread_time;type:bigint unsigned;not null" json:"spread_time"`
	UserType       string                `gorm:"column:user_type;type:varchar(32);not null;comment:用户类型" json:"user_type"`                       // 用户类型
	IsPromoter     int64                 `gorm:"column:is_promoter;type:tinyint unsigned;not null;comment:是否为推广员" json:"is_promoter"`            // 是否为推广员
	PayCount       int64                 `gorm:"column:pay_count;type:int unsigned;not null;comment:用户购买次数" json:"pay_count"`                    // 用户购买次数
	SpreadCount    int64                 `gorm:"column:spread_count;type:int unsigned;not null;comment:下级人数" json:"spread_count"`                // 下级人数
	Addres         string                `gorm:"column:addres;type:varchar(255);not null;comment:详细地址" json:"addres"`                            // 详细地址
	Adminid        int64                 `gorm:"column:adminid;type:int unsigned;not null;comment:管理员编号" json:"adminid"`                         // 管理员编号
	LoginType      string                `gorm:"column:login_type;type:varchar(36);not null;comment:用户登陆类型，h5,wechat,routine" json:"login_type"` // 用户登陆类型，h5,wechat,routine
	LastLoginTime  int64                 `gorm:"column:last_login_time;type:bigint unsigned;not null" json:"last_login_time"`
	CleanTime      int64                 `gorm:"column:clean_time;type:bigint unsigned;not null" json:"clean_time"`
	Path           string                `gorm:"column:path;type:varchar(255);not null;default:/0/;comment:推广等级记录" json:"path"`    // 推广等级记录
	Subscribe      int64                 `gorm:"column:subscribe;type:tinyint unsigned;not null;comment:是否关注公众号" json:"subscribe"` // 是否关注公众号
	SubscribeTime  int64                 `gorm:"column:subscribe_time;type:bigint unsigned;not null" json:"subscribe_time"`
	Sex            int64                 `gorm:"column:sex;type:tinyint unsigned;not null;default:1;comment:性别，0未知，1男，2女，3保密" json:"sex"`    // 性别，0未知，1男，2女，3保密
	Country        string                `gorm:"column:country;type:varchar(20);not null;default:CN;comment:国家，中国CN，其他OTHER" json:"country"` // 国家，中国CN，其他OTHER
	PromoterTime   int64                 `gorm:"column:promoter_time;type:bigint unsigned;not null" json:"promoter_time"`
	CreatedAt      int64                 `gorm:"column:created_at;type:bigint unsigned;not null" json:"created_at"`
	UpdatedAt      int64                 `gorm:"column:updated_at;type:bigint unsigned;not null" json:"updated_at"`
	DeletedAt      soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint unsigned;not null" json:"-"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
