// Code generated by gocli

package eb_system_group_data_model

import (
	"crmeb_go/internal/model"
	"gorm.io/gorm"
	"time"
)

// EbSystemGroupDatumModel 组合数据详情表 模型
type EbSystemGroupDatumModel struct {
	model.DBModel
	ID         uint64    `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:组合数据详情ID" json:"id"`                 // 组合数据详情ID
	Gid        uint64    `gorm:"column:gid;type:int;not null;comment:对应的数据组id" json:"gid"`                                    // 对应的数据组id
	Value      string    `gorm:"column:value;type:text;not null;comment:数据组对应的数据值（json数据）" json:"value"`                      // 数据组对应的数据值（json数据）
	Sort       uint64    `gorm:"column:sort;type:int;not null;comment:数据排序" json:"sort"`                                      // 数据排序
	Status     uint64    `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态（1：开启；2：关闭；）" json:"status"`       // 状态（1：开启；2：关闭；）
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// EbSystemGroupDatumModel 新组合数据详情表 模型实例
func NewEbSystemGroupDatumModel(db *gorm.DB) *EbSystemGroupDatumModel {
	return &EbSystemGroupDatumModel{DBModel: *model.NewDBModel(db, "crmeb", "eb_system_group_data")}
}
